apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: mserver
spec:
  selector:
    matchLabels:
      app: mserver
  replicas: 1
  template:
    metadata:
      labels:
        app: mserver
    spec:
      containers:
      - name: server
        image: maashaik/mserver:latest
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        env:
        - name: REDIS_HOST
          value: $(REDIS_SERVICE_HOST)
        - name: FRONTEND_HOST
          value: $(FRONTEND_SERVICE_HOST)
---