name: CI/CD2

on:
  push:
    branches:
      - prod
  pull_request:
    branches: [ prod ]
    
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: mykube    # Add your cluster name here.
  GKE_ZONE: us-central1-c   # Add your cluster zone here.
  FRONTEND_DEPLOYMENT_NAME: frontend # Add your deployment name here.
  BACKEND_DEPLOYMENT_NAME: backend # Add your deployment name here.

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v3
        
    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}
        
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl get services -o wide
        
    
