name: CI/CD

on:
  push:
    branches:
      - main
      - prod
  pull_request:
    branches: [ prod ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
    
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      
    - name: Test with pytest
      run: |
        pip install -r requirements.txt
        cd chat-server && python test_cases.py
   
    - name: Build frontend
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install # will run `yarn install` command
        
    - name: Build the Docker image
      run: |
        make build
        cd chat-server && make build
      
    - name: Docker Push
      run: |
        make push
        cd chat-server && make push
        
    
